### ISSUE TITLE
As a user, I want to arrive on a landing page, in order to get in the mood for the quiz

### ISSUE THREAD

**Issue by aruppert** [aruppert/quizzle#1]
### Criteria

- [ ] Having an appealing landing page
- [ ] with the app branding
- [ ] and maybe a beautiful animation

### To-Dos

- [ ] Create landing page w/ react router
- [ ] Add app branding
- [ ] Plan an animation and add it
