### ISSUE TITLE
As a user, I want to be able to play with someone else, so we can share the fun 

### ISSUE THREAD

**Issue by aruppert** [aruppert/quizzle#13]
### Criteria

- [ ] 2 player mode on one device  
- [ ] alternating questions for each player
- [ ] final scores of both on one page

### To-Dos

- [ ] 
- [ ]
- [ ]
