### ISSUE TITLE
As a user, I want to answer multiple choice questions, get feedback if I'm right or wrong and get to know the right answer, in order to play and learn

### ISSUE THREAD

**Issue by aruppert** [aruppert/quizzle#2]
### Criteria

- [x] user is presented with questions
- [x] user can choose one of four answers
- [x] only one is correct
- [x] user get's feedback about it's choice
- [ ] right answer is shown

### To-Dos

- [x] create cards with questions and answers (from a db)
- [x] verify the given answer
- [ ] respond with a signal, if user is correct or incorrect
- [ ] mark correct answer (when answered wrongly)
- [x] present next question
