### ISSUE TITLE
As a developer, I want to have a great data structure in my db, so I can implement all possible functions easily with it.

### ISSUE THREAD

**Issue by aruppert** [aruppert/quizzle#29]
### Criteria

- [ ] logic and not too bloated
- [ ] still havening all keys necessary for potential functions
- [ ]

### To-Dos

- [ ] take future features into account
- [ ] write data structure
- [ ] discuss with peers
