### ISSUE TITLE
As a user, I want to determine the length of the game (amount of questions), so I can control the time I need to finish one game

### ISSUE THREAD

**Issue by aruppert** [aruppert/quizzle#3]
### Criteria

- [x] user is able adjust the amount of presented question per game
- [x] preset amounts like e.g. 5, 10 or 15 questions or
- [ ] totally up to the user eg. 1-99

### To-Dos

- [ ] 
- [ ]
- [ ]
