### ISSUE TITLE
As a user, I want to answer questions, so I can play the game

### ISSUE THREAD

**Issue by aruppert** [aruppert/quizzle#4]
### Criteria

- [ ] question and solutions are presented
- [ ] one solutions can be selected
- [ ] solution is submitted (automatically by selection or by clicking a button)

### To-Dos

- [ ] acquire a dataset with questions and answers
- [ ] generate a card with one question and multiple answers
- [ ] add submit and verification functionality for given answer
