### ISSUE TITLE
As a developer, I want to have a design prototype, in order to get a first idea of the layout 

### ISSUE THREAD

**Issue by aruppert** [aruppert/quizzle#6]
### Criteria

- [x]  design prototype in Adobe XD
- [x]  main page layout 
- [x] rough idea for a header and a footer
- [x] simple logo
- [x] font
- [x] basic default colour scheme
- [x] card layout

### To-Dos

- [x] analyse competition 
- [x] find font
- [x] find icon for logo or create a logo 
- [x] choose colours 
- [x] build basic design
- [x] plan how many pages I want to design in this step
